### ISSUE TITLE
Finish moving old wrappers to new workflows

### ISSUE THREAD

**Issue by mhance** [scipp-atlas/mario-mapyde#14]
Now that we have the `mapyde` CLI, I should finish moving the old wrappers to the new workflow.  

- [x] Slepton reinterpretation
- [x] EWKino reinterpretation
- [ ] Monojet
- [ ] Testing different MG versions?
- [ ] VBF SUSY
- [ ] Boosted jets
- [ ] Stops
- [ ] Vjj
- [ ] ttbar

Not all of these need to be ported over, but it would be nice to capture the idiosyncracies in config files.

**Comment by kratsg** [comment]
The tree is here for [v0.1.0](https://github.com/scipp-atlas/mario-mapyde/tree/v0.1.0).

**Comment by mhance** [comment]
EWKino's (with some minor updates for sleptons too) should be done with PR https://github.com/scipp-atlas/mario-mapyde/pull/19.

**Comment by mhance** [comment]
I think I'll close this.  New workflows are easy enough to add at this point, these will get done as they're required.
