### ISSUE TITLE
Fix warnings/errors in pyhf runner

### ISSUE THREAD

**Issue by mhance** [scipp-atlas/mario-mapyde#15]
At the beginning of the pyhf runner, we get an mpl warning that would be nice to address (or suppress):

```Matplotlib created a temporary config/cache directory at /tmp/matplotlib-6rp1fl71 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.```

At the end of running pyhf, we get a crash when trying to make plots:

```
running scan
printing results
Observed limit: 1.095956999359581
Expected limit: 1.105
      -1 sigma: 0.793
      +1 sigma: 1.552
      -2 sigma: 0.600
      +2 sigma: 2.000
making plot
Traceback (most recent call last):
  File "/scripts/muscan.py", line 100, in <module>
    brazil.plot_results(ax, poi_values, results)
  File "/usr/local/lib/python3.8/dist-packages/pyhf/contrib/viz/brazil.py", line 326, in plot_results
    cls_obs = np.array([test[0] for test in tests]).flatten()
  File "/usr/local/lib/python3.8/dist-packages/pyhf/contrib/viz/brazil.py", line 326, in <listcomp>
    cls_obs = np.array([test[0] for test in tests]).flatten()
IndexError: invalid index to scalar variable.
```

**Comment by kratsg** [comment]
Maybe with `pyhf`, we need to run with `MPLCONFIGDIR=/tmp` ? I wonder why the docker image is `/.config` default anyway @matthewfeickert?

**Comment by matthewfeickert** [comment]
@mhance What's the Docker image that you're using? Can you give a minimal example?

**Comment by kratsg** [comment]
https://github.com/scipp-atlas/mario-mapyde/blob/main/Dockerfiles/pyplotting-cuda -- this is the docker image. Seems that the issue is just with this one.

**Comment by kratsg** [comment]
This one is due to the user permissions when we go into the image inside `mapyde`

```
kratsg@slugpu:~$ docker run -it --rm -u $(id -u):$(id -g) ghcr.io/scipp-atlas/mario-mapyde/pyplotting-cuda:latest
groups: cannot find name for group ID 1002
I have no name!@acf4275d0230:/$ python3.8 
Python 3.8.0 (default, Feb 25 2021, 22:10:10) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ub1jf38w because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
```

**Comment by mhance** [comment]
Looks like the brazilband warnings were subtly informing us of some changes in pyhf/contrib:

https://github.com/scikit-hep/pyhf/commit/f6b4198916cc3e4f9afafacfa58c8e69709d2007

Fortunately that was easy to fix.  Now we're left with a residual warning:

```
/usr/local/lib/python3.8/dist-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
```
will look into that next.

**Comment by mhance** [comment]
I don't think that's obviously something that I can fix -- seems to be coming from within the scan.  So I think we can close this issue.
